# Generated by Django 3.2.12 on 2022-05-29 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления'),
        ),
        migrations.AddField(
            model_name='device',
            name='dev_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.devicetype', verbose_name='Тип аппарата'),
        ),
        migrations.AddField(
            model_name='device',
            name='manuf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.manufacturer', verbose_name='Производитель'),
        ),
    ]
