# Generated by Django 3.2.12 on 2022-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='verified',
            field=models.CharField(choices=[('in_progress', 'На модерации'), ('approved', 'Одобрено'), ('declined', 'Требуется редактирование')], default='in_progress', max_length=50),
        ),
    ]
