# Generated by Django 3.2.12 on 2022-06-05 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otivauser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 8, 19, 35, 253135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='otivauser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
