# Generated by Django 3.2.12 on 2022-06-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20220605_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otivauser',
            name='activation_key_expires',
        ),
    ]
