# Generated by Django 3.2.12 on 2022-04-14 15:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_otivauser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otivauser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='otivauser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 6, 47, 388438, tzinfo=utc)),
        ),
    ]
